// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwckkzvijsjelkhtefje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3Y2trenZpanNqZWxraHRlZmplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NDkwOTIsImV4cCI6MjA3MTIyNTA5Mn0.afYJr0s4NVYNFSyy3JT0nuCORfkkBHxJ53JX6_bRFYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});